# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements_ip.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements_ip.txt

# Copy the rest of the application code into the container
COPY image_processor.py .

# Expose the port the app runs on
EXPOSE 5025

# Run the application
CMD ["python", "image_processor.py"]
